name: Build the project on linux

on: push

jobs:
  build_qt5:
    name: Build ubuntu-20.04 glibmm-2.4 Qt5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - run: sudo apt-get install -y default-jdk build-essential cmake wget unzip pkg-config autoconf libtool sdcc qt5-default libzip-dev libglibmm-2.4-dev doxygen gir1.2-gtk-3.0 qttools5-dev qttools5-dev-tools libgirepository1.0-dev libcairo2-dev pkg-config python3-dev libqt5svg5-dev libboost-all-dev libusb-1.0-0-dev libftdi1-dev libieee1284-3-dev nettle-dev libhidapi-dev python3-pip python-gi-dev python3-numpy python3-setuptools bluez check libbluetooth-dev autoconf-archive

      - run: pip3 install -I pycairo PyGObject

      - name: sigrok-cross-linux
        run: |
          cd cross-compile/linux
          ./sigrok-cross-linux

      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-20.04_qt_5
          path: ~/sr

  build_qt6:
    name: Build ubuntu-22.04 glibmm-2.4 Qt6
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master

      - run: sudo apt-get install default-jdk build-essential cmake wget unzip pkg-config autoconf libtool sdcc qt6-base-dev qt6-base-dev-tools libzip-dev libglibmm-2.4-dev doxygen gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev pkg-config python3-dev libqt6svg6-dev libboost-all-dev libusb-1.0-0-dev libftdi1-dev libieee1284-3-dev nettle-dev libhidapi-dev python3-pip python-gi-dev python3-numpy python3-setuptools bluez check libbluetooth-dev autoconf-archive libqt6gui6

      - run: pip3 install -I pycairo PyGObject

      - name: sigrok-cross-linux
        run: |
          cd cross-compile/linux
          ./sigrok-cross-linux

      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-22.04_qt_6
          path: ~/sr
