name: Build the project on linux

on: push

jobs:
  build:
    name: Build linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential cmake wget unzip pkg-config autoconf libtool sdcc qt5-default libzip-dev libglibmm-2.4-dev doxygen python3-gi python3-gi-cairo gir1.2-gtk-3.0

      - name: Build
        run: |
          cd cross-compile/linux
          ./sigrok-cross-linux
